export enum DietaryRestrictionsEnum {
    LACTOSE_INTOLERANCE = 'LACTOSE_INTOLERANCE',
    GLUTEN_INTOLERRANCE = 'GLUTEN_INTOLERANCE',
    NUT_ALLERGY = 'NUT_ALLERGY',
    SEAFOOD_ALLERGY = 'SEAFOOD_ALLERGY'
}