export enum DietaryRestrictionsEnum {
    LACTOSE_INTOLERANCE = 'lLACTOSE_INTOLERANCE',
    GLUTEN_INTOLERRANCE = 'GLUTEN_INTOLERRANCE',
    NUT_ALLERGY = 'NUT_ALLERGY',
    SEAFOOD_ALLERGY = 'SEAFOOD_ALLERGY'
}